openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0

paths:
  /v1/validate:
    post:
      summary: Validate a token
      operationId: Validate
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
      responses:
        '200':
          description: Token validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ValidateRequest:
      type: object
      required: [token]
      properties:
        token:
          type: string
          description: JWT token

    ValidateResponse:
      type: object
      properties:
        valid:
          type: boolean
          description: Whether the token is valid

    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: string
          example: "invalid credentials"